# Generated by Django 5.2.1 on 2025-06-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_alter_avatar_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
