# Generated by Django 5.2.3 on 2025-07-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_auth', '0003_alter_profile_options'),
        ('api_product', '0006_product_datefrom_product_dateto_product_saleprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'EXPRESS_DELIVERY_COST',
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=10,
                        verbose_name='Стоимость экспресс-доставки',
                    ),
                ),
                (
                    'FREE_DELIVERY_THRESHOLD',
                    models.DecimalField(
                        decimal_places=2,
                        default=2000,
                        max_digits=10,
                        verbose_name='Порог бесплатной доставки',
                    ),
                ),
                (
                    'REGULAR_DELIVERY_COST',
                    models.DecimalField(
                        decimal_places=2,
                        default=200,
                        max_digits=10,
                        verbose_name='Стоимость обычной доставки',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'createdAt',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
                (
                    'deliveryType',
                    models.CharField(default='', max_length=255, verbose_name='Тип доставки'),
                ),
                (
                    'paymentType',
                    models.CharField(default='', max_length=255, verbose_name='Тип оплаты'),
                ),
                (
                    'totalCost',
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа'
                    ),
                ),
                (
                    'status',
                    models.CharField(default='', max_length=255, verbose_name='Статус заказа'),
                ),
                ('city', models.CharField(default='', max_length=255, verbose_name='Город')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to='api_auth.profile',
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'price',
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
                ),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='api_order.order',
                        verbose_name='Заказ',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_items',
                        to='api_product.product',
                        verbose_name='Товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(
                related_name='orders',
                through='api_order.OrderItem',
                to='api_product.product',
                verbose_name='Товары',
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-createdAt'], name='api_order_o_created_2ebf23_idx'),
        ),
    ]
