# Generated by Django 5.2.3 on 2025-07-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_alter_profile_options'),
        ('api_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Ключ сессии'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='orders',
                to='api_auth.profile',
                verbose_name='Пользователь',
            ),
        ),
    ]
