# Generated by Django 5.2.3 on 2025-08-05 10:48

import api_product.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
                ),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='subcategories',
                        to='api_product.category',
                        verbose_name='Родительская категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'src',
                    models.ImageField(
                        upload_to=api_product.models.category_image_directory_path,
                        verbose_name='Изображение',
                    ),
                ),
                ('alt', models.CharField(default='image', max_length=64, verbose_name='Описание')),
                (
                    'category',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='image',
                        to='api_product.category',
                        verbose_name='Категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name='Цена'
                    ),
                ),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                (
                    'date',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='Дата создания'
                    ),
                ),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                (
                    'fullDescription',
                    models.TextField(blank=True, null=True, verbose_name='Полное описание'),
                ),
                (
                    'freeDelivery',
                    models.BooleanField(default=True, verbose_name='Бесплатная доставка'),
                ),
                (
                    'reviews_count',
                    models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
                ),
                (
                    'rating',
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name='Рейтинг'
                    ),
                ),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                (
                    'salePrice',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name='Цена со скидкой',
                    ),
                ),
                (
                    'dateFrom',
                    models.DateTimeField(blank=True, null=True, verbose_name='Дата начала акции'),
                ),
                (
                    'dateTo',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Дата окончания акции'
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to='api_product.category',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        blank=True,
                        related_name='products',
                        to='api_product.tag',
                        verbose_name='Теги',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'src',
                    models.ImageField(
                        upload_to=api_product.models.product_image_directory_path,
                        verbose_name='Изображение',
                    ),
                ),
                ('alt', models.CharField(default='image', max_length=64, verbose_name='Описание')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='api_product.product',
                        verbose_name='Товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('value', models.CharField(max_length=128, verbose_name='Значение')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='specifications',
                        to='api_product.product',
                        verbose_name='Товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'rate',
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name='Оценка',
                    ),
                ),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='api_product.product',
                        verbose_name='Товар',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('product', 'user'), name='unique_product_user_review'
                    )
                ],
            },
        ),
    ]
