# Generated by Django 5.2.1 on 2025-06-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
