# Generated by Django 5.2.1 on 2025-06-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0003_review_unique_product_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api_product.category', verbose_name='Категория'),
        ),
    ]
