# Generated by Django 5.2.3 on 2025-06-28 08:15

from django.db import migrations, models


def set_available_based_on_count(apps, schema_editor):
    """
    Устанавливает значение поля 'available' для существующих продуктов:
    - True, если count > 0
    - False, если count == 0
    """
    Product = apps.get_model(
        'api_product', 'Product'
    )  # Получаем модель Product через historical модель
    # Обновляем поле 'available' для продуктов, где количество больше 0
    Product.objects.filter(count__gt=0).update(available=True)
    # Обновляем поле 'available' для продуктов, где количество равно 0
    Product.objects.filter(count=0).update(available=False)


class Migration(migrations.Migration):
    """
    Миграция для добавления поля 'available' и установки его значения
    на основе поля 'count' для существующих записей.
    """

    dependencies = [
        ('api_product', '0004_alter_categoryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        # Запускаем кастомную функцию для корректного заполнения поля 'available'
        migrations.RunPython(set_available_based_on_count),
    ]
