# Generated by Django 5.2.3 on 2025-07-07 13:12

import datetime
from django.db import migrations, models


def set_sale_fields(app, schema_editor):
    Product = app.get_model('api_product', 'Product')

    Product.objects.filter(title='Smartphone').update(
        salePrice=799.99,
        dateFrom=datetime.datetime(2025, 7, 1),
        dateTo=datetime.datetime(2025, 7, 31),
    )

    Product.objects.filter(title='Laptop').update(
        salePrice=1999.99,
        dateFrom=datetime.datetime(2025, 7, 1),
        dateTo=datetime.datetime(2025, 7, 31),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0005_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateFrom',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Цена со скидкой',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.RunPython(set_sale_fields),
    ]
