name: CI for develop branch
run-name: ${{ github.actor }} is starting Push request testing on branch ${{ github.ref_name }}

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '2.1.0'

      - name: Install dependencies
        run: poetry install

      - name: Run black check
        run: poetry run black --check --diff --color
